### ISSUE TITLE
Babel error on converting .es6 file

### ISSUE THREAD

**Issue by Altiano** [thejameskyle/jekyll-babel#4] opened 2015-12-26 13:04 UTC
I have install babel-jekyll and  execjs.
I also has set the _config.yml file and use front matter in .es6 file but I'm getting this error
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/8316282/12006481/424823a0-ac14-11e5-8645-24395eb7673b.png">

**Comment by jamiebuilds** [comment] 2015-12-26 22:01
Unable to reproduce, here's a working example: https://github.com/thejameskyle/jekyll-babel-example

Closing this, but if you can create a repo that reproduces this issue I'll gladly take a look.

**Closed as completed by jamiebuilds** 2015-12-26 22:01 UTC

**Comment by Altiano** [comment] 2015-12-27 04:10
The working example not working either.
![image](https://cloud.githubusercontent.com/assets/8316282/12008807/86410d3c-ac92-11e5-90d7-7858601f8144.png)

I've added you to collaborators in my repo.
This is just new repo so nothing special yet

**Comment by jamiebuilds** [comment] 2015-12-27 04:13
Seems like an issue with windows, I'll check it out on my other machine

**Comment by jamiebuilds** [comment] 2015-12-27 07:40
I have been trying to get ruby/rubygems/bundler/jekyll for hours and can't get anything working (I seriously don't know how anyone develops anything on windows machines).

I'm afraid I can't really help you here, hopefully someone else comes along that knows more, or you're able to find the source of the problem.

**Comment by Altiano** [comment] 2015-12-27 08:11
I have Ubuntu, maybe it will work there.
Please tell me if you've figured that out.
Thank you :)
